"""Constants for the Sanremo Cube integration."""

DOMAIN = "sanremo_cube"

CONF_PIN = "pin"

DEFAULT_SCAN_INTERVAL = 15  # seconds
DEFAULT_TIMEOUT = 8  # seconds

ENDPOINT = "/default.aspx/PostAction"

# --- reqCode values (from cube.js) ---
REQ_LOGIN = "100"
REQ_LOGOUT = "101"
REQ_SCAN_NETWORKS = "102"
REQ_CONNECT_WIFI = "103"
REQ_SET_DHCP = "104"
REQ_GET_DEVICE_INFO = "105"
REQ_GET_SYSTEM_PARAMETERS = "150"
REQ_GET_READONLY_PARAMETERS = "151"
REQ_GET_READWRITE_PARAMETERS = "152"
REQ_SET_VALUE = "200"
REQ_REBOOT = "202"
REQ_SET_RTC = "249"
REQ_SET_SCHEDULER_DAY_STATUS = "250"
REQ_SET_MACHINE_NAME = "251"
REQ_SET_SCHEDULER_STATUS = "252"
REQ_SAVE_SCHEDULER_DAY = "253"
REQ_SET_APP_DATA = "255"

# --- id values for the generic setter (reqCode 200) ---
ID_BOILER_TEMPERATURE = 1
ID_STANDBY_EXCLUSIVE = 8
ID_ECO_EXCLUSIVE = 9
ID_ECO_MODE = 10
ID_STANDBY_ON = 11
ID_POWER_ON = 12
ID_ENABLE_CLOCK = 20
ID_TEMPERATURE_UNIT = 21
ID_FILTER_REPORTING_MONTHS = 22
ID_RESET_FILTER_EXPIRATION = 23
ID_STEAM_BOOSTER = 24
ID_ECO_TIMER_SECONDS = 25
ID_ECO_BOILER_SETPOINT_X10 = 26

# --- readonly register indices (from ReadWinetGetSystemParametersCompleted-style parsing) ---
REG_BOILER_TEMPERATURE = 0
REG_RTC_MINUTE = 2
REG_RTC_HOUR = 3
REG_RTC_DAY = 4
REG_RTC_MONTH = 5
REG_RTC_YEAR = 6
REG_SETPOINT_BOILER_TEMPERATURE_X10 = 8
REG_EROGATION_COFFEE_TIME_X10 = 9
REG_REMAIN_DAYS_TO_FILTER = 10
REG_MACHINE_STATUS_1 = 12
REG_MACHINE_ALARM_STATUS_1 = 14
REG_SETUP_FLAGS = 17
REG_DAY_COFFEE = 21
REG_WEEK_COFFEE = 22
REG_MONTH_COFFEE_LOW = 23
REG_MONTH_COFFEE_HIGH = 24
REG_YEAR_COFFEE_LOW = 25
REG_YEAR_COFFEE_HIGH = 26
REG_TOT_COFFEE_LOW = 29
REG_TOT_COFFEE_HIGH = 30
REG_TOT_ML_EROGATED_LOW = 31
REG_TOT_ML_EROGATED_HIGH = 32
REG_TOT_ML_LOADED_BOILER_LOW = 33
REG_TOT_ML_LOADED_BOILER_HIGH = 34
REG_TOT_ML_LOW = 35
REG_TOT_ML_HIGH = 36
REG_SCHEDULER_DAY_ENABLED_MASK = 60
REG_ECO_TIMER_SECONDS = 67
REG_ECO_BOILER_SETPOINT_X10 = 68

# scheduler day/time-on/time-off table: 7 days x 3 slots, registers 18..59
REG_SCHEDULER_TABLE_START = 18
SCHEDULER_SLOT_COUNT = 21  # 7 days * 3 slots

# Setup bitmask (register 17) bit positions, best-effort from cube.js
SETUP_BIT_TEMPERATURE_UNIT = 2
SETUP_BIT_SCHEDULER_ENABLED = 3
SETUP_BIT_WIFI_CIRCUIT_ENABLED = 4
SETUP_BIT_PRE_INFUSION_ENABLED = 5
SETUP_BIT_ECO_ENABLED = 6
SETUP_BIT_STEAM_BOOSTER_ENABLED = 7

# MachineStatus1 (register 12) bit positions
STATUS_BIT_TANK_LEVEL_OK = 0
STATUS_BIT_WATER_SOURCE = 3  # 1 bit, shifted
STATUS_BIT_ENERGY_SAVING = 4
STATUS_BIT_READY = 5
STATUS_BIT_STEAM_BOOSTER_HEATING = 8
STATUS_BIT_STEAM_BOOSTER_SETPOINT_OK = 9

# MachineAlarmStatus1 (register 14) bit positions
ALARM_BIT_NTC_BOILER_BROKEN = 0
ALARM_BIT_TEMPERATURE_TIMEOUT = 1
ALARM_BIT_LOAD_BOILER_TIMEOUT = 2
ALARM_BIT_NTC_BOILER_SHORT_CIRCUIT = 3
ALARM_BIT_EEPROM_ERROR = 4
ALARM_BIT_WIREWOUND_RESISTOR = 5
ALARM_BIT_EROGATION_TIMEOUT = 6
ALARM_BIT_NEED_CHANGE_FILTERS = 7

WEEKDAYS = ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"]
